// flow-typed signature: 88ca46375067b6d0801fa6c6d46353c2
// flow-typed version: <<STUB>>/redux-webext_v^1.1.2/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-webext'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-webext' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-webext/lib/background-store' {
  declare module.exports: any;
}

declare module 'redux-webext/lib/constants' {
  declare module.exports: any;
}

declare module 'redux-webext/lib/index' {
  declare module.exports: any;
}

declare module 'redux-webext/lib/ui-store' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-webext/lib/background-store.js' {
  declare module.exports: $Exports<'redux-webext/lib/background-store'>;
}
declare module 'redux-webext/lib/constants.js' {
  declare module.exports: $Exports<'redux-webext/lib/constants'>;
}
declare module 'redux-webext/lib/index.js' {
  declare module.exports: $Exports<'redux-webext/lib/index'>;
}
declare module 'redux-webext/lib/ui-store.js' {
  declare module.exports: $Exports<'redux-webext/lib/ui-store'>;
}
